apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secret-operator
  namespace: aws-secret-operator
  labels:
    app: aws-secret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-secret-operator
  template:
    metadata:
      labels:
        app: aws-secret-operator
    spec:
      containers:
        - name: aws-secret-operator
          image: ecr-repo/aws-secret-operator:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-credentials
                  key: aws_secret_access_key
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-secret-config
                  key: region
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 8080
