apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  namespace: health-checks
spec:
  selector:
    app: datadog-agent
  ports:
    - protocol: TCP
      port: 8126
      targetPort: 8126
      name: apm
    - protocol: TCP
      port: 8125
      targetPort: 8125
      name: dogstatsd
  type: ClusterIP
