apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-app-deployment
  namespace: mono-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mono-app
  template:
    metadata:
      labels:
        app: mono-app
    spec:
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: production
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
        - name: backend
          image: python:3.9
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: production
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
