apiVersion: v1
kind: Service
metadata:
  name: mono-app-service
  namespace: mono-app
spec:
  selector:
    app: mono-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
