apiVersion: v1
kind: Service
metadata:
  name: github-actions-runner-service
  namespace: github-actions
  labels:
    app: github-actions-runner
spec:
  selector:
    app: github-actions-runner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
