apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: hashicorp-vault
  labels:
    app: vault-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      containers:
        - name: vault-agent
          image: hashicorp/vault:latest
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-credentials
                  key: vault_token
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: vault_addr
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
        - name: vault-port
          ports:
            - containerPort: 8200
