apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Argo-Demo/repo'
    path: ./declarative/manifests/base-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  apps:
    - name: frontend
      path: apps/frontend
    - name: backend
      path: apps/backend
