apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/example/repo'
    path: ./declarative/manifests/frontend-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend
  retrySyncPolicy:
    automated:
      prune: true
      selfHeal: true
  retry:
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
    limit: 5
    automated:
      prune: true
      selfHeal: true
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
